version: '3.8'

services:
  web-scraper:
    build: .
    container_name: web-scraper-service
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
